version: '3.9'

services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    ports:
      - 9191:80
    volumes:
      - nextcloud_config:/config
      - /srv/dev-disk-by-uuid-72B848C2B8488697:/mnt/storage
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - plex_config:/config
      - /srv/dev-disk-by-uuid-72B848C2B8488697:/data
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    ports:
      - 8112:8112
    volumes:
      - deluge_config:/config
      - /srv/dev-disk-by-uuid-72B848C2B8488697:/downloads
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr
    container_name: overseerr
    ports:
      - 5055:5055
